# Generated by Django 4.1.3 on 2022-12-01 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название отдела')),
            ],
        ),
        migrations.CreateModel(
            name='Rabotnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Фамилия Имя Отчество')),
                ('post', models.CharField(max_length=60, verbose_name='Должность')),
                ('salary', models.FloatField(blank=True, null=True, verbose_name='Зарплата')),
                ('departament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='worker.departament', to_field='name')),
            ],
            options={
                'verbose_name': 'WORKER',
                'verbose_name_plural': 'WORKERS',
                'unique_together': {('name', 'post')},
            },
        ),
    ]
